Lunson.Web/Lunson.Web/Controllers/BookLetController.cs
using Lunson.BLL.Services;
using Lunson.Web.Models;
using Pharos.Framework;
using Pharos.Framework.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lunson.Web.Controllers
{
    [CheckLogin]
    public class BookLetController : BaseController
    {
        TicketService tsv = new TicketService();

        public ActionResult Index()
        {
            var availableTickets = tsv.GetTicketDetailByUser(customerCache.CustomerID);
            //var availableTicketPage = availableTickets.OrderBy(a=>a.CreatedOn).ToPagedList(p_available ?? 1, 1);
            return View(availableTickets.OrderBy(p=>p.CreatedOn));
        }

        public ImageResult QR(string id)
        {
            var detailNos = id.Split(',').Where(a => a.IsNullOrTrimEmpty() == false).Distinct().ToList();

            detailNos = tsv.GetAvailableTicketNos(detailNos, customerCache.CustomerID);
            if (detailNos.Any())
            {
                QRCodeHelper.GetQRCode(string.Join(",", detailNos.Take(5)), Response);
            }

            return new ImageResult();
        }

    }
}

Lunson.Web/Lunson.Web/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lunson.BLL.Services;
using Lunson.Web.Models;
using Lunson.Domain;
using Pharos.Framework;

namespace Lunson.Web.Controllers
{
    public class TicketController : Controller
    {
        TicketService tsv = new TicketService();
        /// <summary>
        /// 票列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var data = tsv.GetAvailableIncludeTickets();
            return View(data.ToList());
        }
        /// <summary>
        /// 购买明细
        /// </summary>
        /// <param name="ID">票ID</param>
        /// <param name="Num">数量</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult TicketDetails(string ID, string Num = "1")
        {
            var dic = DataHelper.ToDic<int>(ID, Num, ',');

            if (dic.Any())
            {
                return View(tsv.GetTicketCart<TicketDetailVM>(dic));
            }

            return RedirectToAction("Index");
        }
        /// <summary>
        /// 根据ID加载门票详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult TicketParticular(string id)
        {
            ViewBag.imgs = new AnnexService().GetAnnexes(AnnexType.Crocodile).OrderBy(a => Guid.NewGuid()).Take(6);
            var data = tsv.GetTicket(id, "Annex");
            //var data = tsv.TicketParticular(id);
            if (data == null)
                return RedirectToAction("Index");
            return View(data);
        }


        
        /// <summary>
        /// 退票
        /// </summary>
        /// <param name="nos"></param>
        /// <returns></returns>
        [CheckLogin]
        public ActionResult Refund(string nos)
        {
            CustomerCache cache = new CustomerCache();
            return Json(tsv.Refund(nos,cache.CustomerID));
        }

        public ActionResult Help()
        {
            return View();
        }
    }
}

Lunson.Web/Lunson.Web/Views/Shared/404.cshtml
<h2 style="padding:20px;font-size:1.4em;">很抱歉，您要访问的页面不存在！</h2>

Lunson.Web/Lunson.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>南顺鳄鱼园 @(ViewBag.Title)</title>
    <meta name="keywords" content="鳄鱼园, 南顺鳄鱼园, 厦门南顺鳄鱼园, 鳄鱼制品, 鳄鱼药物, 鳄鱼美食, 旅游产业, 国家3A级景区, 中国最大室内鳄鱼园">
    <meta name="description" content="@ViewBag.Description">
    <script src="@Url.Content("~/Scripts/jquery/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/pharos.js")"></script>
    <link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/default/global.css")" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <div class="wrap">
            <div class="w1000">
                @Html.Partial("_PartialNav")
            </div>
        </div>
    </div>

    <div class="w1000 clearfix">
        <div class="fl-l clearfix leftnav">
            @Html.Partial("_PartialWeather")
            @Html.Partial("_PartialHomeMenu")
            @Html.Partial("_PartialMessage")
            @Html.Partial("_PartialLink")
        </div>
        <div class="fl-r clearfix rightcontent">
            @RenderBody()
        </div>
    </div>

    <div class="footer">
        电话：0592-6068699   传真：0592-6068100  地址：厦门集美旅游商城A幢鳄鱼园大厦  闽ICP备05024499号-1
        <a target="_blank" href="/backend/Account/login">管理</a>
        <a href="http://www.xmpharos.com" target="_blank" style="margin-left:20px;">
            <img src="~/Content/default/images/home/footer_logo.png" style="vertical-align:middle;" />
        </a>
    </div>
    <div class="m-btk">
        <div class="item1"></div>
        <div class="item2"></div>
    </div>

    <script>
        $(function () {
            $(".m-btk").click(function () {
                window.location = "@Url.Action("Index","Ticket")";
            });
            $(".m-btk").mouseover(function () {
                $(".m-btk .item1").stop().animate({ bottom: 50 }, 300);
            });
            $(".m-btk").mouseout(function () {
                $(".m-btk .item1").stop().animate({ bottom: 0 }, 300);
            });


        })
    </script>
    <!--[if lte  IE 6]>
        <script>
            $(function () {
                resetbtk();
                $(window).scroll(function () {
                    resetbtk();
                });

            })

            function resetbtk() {
                $(".m-btk").stop().animate({ bottom: 50 - document.body.scrollTop }, 500);
            }
        </script>
    <![endif]-->

</body>
</html>

Lunson.Web/Lunson.Web/Views/Shared/_LayoutMobile.cshtml
<!DOCTYPE html>

<html style="*overflow:auto;">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>南顺鳄鱼园 - 手机购票</title>
    <script src="@Url.Content("~/Scripts/jquery/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/pharos.js")"></script>
    <link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Scripts/magnific-popup/magnific-popup.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/magnific-popup/jquery.magnific-popup.js")"></script>

    <link href="@Url.Content("~/Content/mobile/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <link href="@Url.Content("~/Content/mobile/mobile.css")" rel="stylesheet" />
</head>
<body style="_overflow:auto;">
    <div style="height: 5%;">
        <div style="background-color: #b9cc4c; width: 100%; text-align: center; font-size: 1.25em; line-height: 50px; color: #FFFFFF; font-family: 'Microsoft YaHei'; ">
            <div style="height:21px; width:14px; margin-top:15px; float:left"></div>
            <span>南顺鳄鱼园</span>
            <img src="~/Content/default/images/logo.png" style=" height:26px; width:30px;right:10px;top:13px;position:absolute;" />
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("_PartialUserFooter")
</body>
</html>

Lunson.Web/Lunson.Web/Views/Shared/_LayoutMobile_Index.cshtml
<!DOCTYPE html>

<html style="*overflow:auto;">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>南顺鳄鱼园 - 手机购票</title>
    <script src="@Url.Content("~/Scripts/jquery/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/pharos.js")"></script>
    <link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Scripts/magnific-popup/magnific-popup.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/magnific-popup/jquery.magnific-popup.js")"></script>

    <link href="@Url.Content("~/Content/mobile/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <link href="@Url.Content("~/Content/mobile/mobile.css")" rel="stylesheet" />
</head>
<body style="_overflow:auto;">
    
        
  
   
        @RenderBody()
  
    @Html.Partial("_PartialUserFooter")
</body>
</html>

Lunson.Web/Lunson.Web/Views/Shared/_LayoutUserInfo.cshtml
<!DOCTYPE html>

<html style="*overflow:auto;">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/pharos.js")"></script>
    <link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/default/userinfo.css")" rel="stylesheet" />
</head>
<body style="_overflow:auto;">
    <div id="container">
        <div class="header">
            <div class="wrap">
                <div class="w1000">
                    <span class="logo">南顺鳄鱼园</span>
                    <a class="url" href="/">www.losnun.com.cn</a>
                    @Html.Partial("_PartialLogin")
                    @Html.Partial("_PartialUserNav")
                </div>
            </div>
        </div>

        @RenderBody()
    </div>
    @Html.Partial("_PartialUserFooter")
</body>
</html>

Lunson.Web/Lunson.Web/Views/Shared/_PartialHomeMenu.cshtml
<div class="menu">
    <ul>
        <li>
            <a href="/Introduction" data-nav="introduction">园区介绍</a>
        </li>
        <li>
            <a href="/Visit" data-nav="visit">园区参观</a>
        </li>
        <li>
            <a href="/Transitlines" data-nav="transitlines">交通线路</a>
        </li>
        <li>
            <a href="/Notice" data-nav="notice">游园须知</a>
        </li>
        <li>
            <a href="/GrowingUp" data-nav="growingup">成长过程</a>
        </li>
        <li>
            <a href="/HumanResources" data-nav="humanresources">人力资源</a>
        </li>
        <li>
            <a href="/ContactUs" data-nav="contactus">联系我们</a>
        </li>
    </ul>
</div>

Lunson.Web/Lunson.Web/Views/Shared/_PartialLink.cshtml
<div style="margin-top: 10px; margin-bottom: 10px; font-size: 1.1em; color: #725c37;">友情链接</div>
<ul class="links">
    @foreach (var x in new Lunson.BLL.Services.LinkService().GetLinks().Where(a=>a.ActiveState==Lunson.Domain.ActiveState.Normal&&a.Annex!=null))
    { 
    <li>
        <a href="@x.LinkUrl" target="_blank" title="@x.Title">
            <img src="@x.Annex.Url" width="121" height="35"/>
        </a>
    </li>
    }
</ul>

Lunson.Web/Lunson.Web/Views/Shared/_PartialLogin.cshtml
@{
    var customer = new Lunson.Web.CustomerCache();

}

<div class="user">
    @if (customer.IsLogin == false)
    {
        <a href="@Url.Action("Login","Account")">[登录]</a>
        <a href="@Url.Action("Register", "Account")">[注册]</a>
    }
    else
    {
        <span>您好，</span>
        <a href="@Url.Action("Index", "BookLet")">@HttpUtility.UrlDecode(customer.DisplayName)</a>
        <a href="@Url.Action("Logout", "Account")">[退出]</a>
    }
</div>

Lunson.Web/Lunson.Web/Views/Shared/_PartialMessage.cshtml
<div class="showtime">
    <h1>人鳄表演时间</h1>
    <table>
        <tr>
            <td style="border-right: solid 1px #71531d; border-bottom: solid 1px #71531d; width:60px;">周一、周三</td>
            <td style="border-bottom: solid 1px #71531d; ">下午暂无</td>
        </tr>
        <tr>
            <td style="border-right: solid 1px #71531d;">周四至周日</td>
            <td >上午暂无<br />下午暂无</td>
        </tr>
    </table>

    <h1>门票价格</h1>
    <table>
        <tr>
            <td style="border-right: solid 1px #71531d; width: 60px; border-bottom: solid 1px #71531d; ">普通门票</td>
            <td style="border-bottom: solid 1px #71531d; "> 大人 30元/人<br />儿童 15元/人</td>
        </tr>
        <tr>
            <td style="border-right: solid 1px #71531d;">	鳄鱼表演门票</td>
            <td>大人 60元/人<br />儿童 30元/人</td>
        </tr>
    </table>
</div>

<div class="phone">
    <p class="shophours">营业时间：8:00-18:00</p>
    <p class="tickethotline">订票热线：0592-6068699</p>
</div>

Lunson.Web/Lunson.Web/Views/Shared/_PartialNav.cshtml
<div class="nav">
    <a href="/PressRelease" data-nav="company">公司资讯</a>
    <a href="/Products" data-nav="products">鳄鱼制品</a>
    <a href="/Performance" data-nav="performance">园区表演</a>
    <a href="/Medicine" data-nav="medicine">鳄鱼药物</a>
    <a href="/Delicious" data-nav="delicious">鳄鱼美食</a>
    <a href="/Science" data-nav="science">科普园区</a>
    <a href="/Pilot" data-nav="pilot">标准化试点</a>
    <a href="/Ticket" class="last">网上购票</a>
</div>

Lunson.Web/Lunson.Web/Views/Shared/_PartialUserFooter.cshtml
    <div class="footer">
        <div class="wrap">
            <div class="w1000">
                <p>电话：0592-6068699 &nbsp;&nbsp; 传真：0592-6068100</p>
                <p>地址：厦门集美旅游商城A幢鳄鱼园大厦</p>
                <p>版权所有 闽ICP备05024499号-1</p>
            </div>
        </div>
    </div>

<script>
    $(function () {
        //resetfooter();
       // setInterval(resetfooter,1000);
    })

    function resetfooter() {
        var h = $("#container").height();
        var htemp = $(window).height();
        if (h < htemp + 100) {
            $(".footer").css("margin-top", htemp - h-100);
        }
        else {
            $(".footer").css("margin-top", 0);
        }
    }
</script>

Lunson.Web/Lunson.Web/Views/Shared/_PartialUserNav.cshtml
<ul class="nav clearfix">
    <li style="*width:36px;"><a href="/" class="home">首页</a></li>
    <li style="*width:100px;" class="@(ViewBag.nav == "wallet" ? "active" : "")"><a href="/BookLet" class="wallet">我的票夹</a></li>
    <li style="*width:60px;" class="@(ViewBag.nav == "buyticket" ? "active" : "")"><a href="/ticket" class="buyticket">购票</a></li>
    <li style="*width:100px;" class="@(ViewBag.nav == "myaccount" ? "active" : "")"><a href="/Account" class="wallet">我的帐号</a></li>
    <li style="*width:100px;" class="@(ViewBag.nav == "help" ? "active" : "")"><a href="/ticket/help" class="wallet">购票帮助</a></li>
</ul>

Lunson.Web/Lunson.Web/Views/Shared/_PartialWeather.cshtml
<div id="weather">
    <h1>天气预报</h1>
    <p class="time">@DateTime.Now.ToString("yyyy年MM月dd日")</p>
    <iframe width="170" scrolling="no" height="18" frameborder="0" allowtransparency="true" src="http://i.tianqi.com/index.php?c=code&id=1&icon=4&wind=1&num=1"></iframe>
</div>