Lunson.Web/Lunson.Web/Areas/Backend/Controllers/FeedController.cs
using Lunson.BLL.Services;
using Lunson.Domain;
using Lunson.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Pharos.Framework;
using Pharos.Framework.MVC;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Web.Script.Serialization;

namespace Lunson.Web.Areas.Backend.Controllers
{
    public class FeedController : BaseController
    {
        public FeedService fsv = new FeedService();

        [PermissionCheck("view", "index")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetFeeds(int? page, int? rows)
        {
            var feeds = fsv.GetFeeds();

            var pagelist = feeds.OrderByDescending(a => a.PublishOn).Skip(((page ?? 1) - 1) * (rows ?? 20)).Take(rows ?? 20).ToList()
                .Select(a => new
                {
                    a.ID,
                    a.ActiveState,
                    a.Author,
                    a.ClickNum,
                    FeedTypeName = a.FeedType == null ? "" : a.FeedType.Name,
                    a.ShowOrder,
                    a.Title,
                    a.Original,
                    a.IsRecommend,
                    a.IsTop,
                    a.PublishOn
                });

            //var json =  JsonConvert.SerializeObject(new { total = feeds.Count(), rows = pagelist });
            //return json;
            return Json(new { total = feeds.Count(), rows = pagelist });
        }
        [HttpPost]
        [PermissionCheck("delete", "index")]
        public ActionResult RemoveFeed(string id)
        {
            fsv.RemoveFeed(id, UserCache.CurrentUser.Id);
            return Json("");
        }

        [PermissionCheck("edit", "index")]
        public ActionResult FeedManageForm(string id)
        {
            var feed = fsv.GetFeed(id);
            if (feed == null)
                feed = new Feed { ActiveState = ActiveState.Frozen };

            ViewBag.feedtypes = fsv.GetFeedType(feed.FeedTypeID);

            return View(feed);
        }

        [HttpPost]
        [ValidateInput(false)]
        [PermissionCheck("edit", "index")]
        public ActionResult SaveData(Feed feed)
        {
            if (feed.Title.IsNullOrTrimEmpty())
            {
                return Json(new { validate = false, target = "Title", msg = "标题不能为空" });
            }

            var result = fsv.SaveFeed(feed, UserCache.CurrentUser.Id);
            return Json(result);
        }

        //// simditor
        //[HttpPost]
        //[ValidateInput(false)]
        //public ActionResult Upload()
        //{
        //    try
        //    {
        //        if (Request.Files.Count == 0)
        //            throw new Exception("查无上传的文件");
        //        var file = Request.Files[0];


        //        if (PictureHelper.IsSecureUploadPhoto(file) == false)
        //            throw new Exception("图片格式不正确：gif png jpeg jpg bmp");

        //        var annew = fsv.SaveFeedPicture(file, UserCache.CurrentUser.Id);
        //        return Json(new { success = true, msg = "上传成功", file_path = annew.Url });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { success = false, msg = ex.Message, file_path = "" });
        //    }

        //}

        /// <summary>
        /// 文章查询
        /// </summary>
        /// <param name="title"></param>
        /// <param name="type"></param>
        /// <param name="beginTime"></param>
        /// <param name="endTime"></param>
        /// <param name="page"></param>
        /// <param name="rows"></param>
        public ActionResult SearchFeeds(string title, string type, DateTime? beginTime, DateTime? endTime, int? page, int? rows)
        {
            var feeds = fsv.GetFeeds();

            if (!title.IsNullOrTrimEmpty())
                feeds = feeds.Where(f => f.Title.Contains(title));
            if (!type.IsNullOrTrimEmpty())
                feeds = feeds.Where(f => f.FeedTypeID.Equals(type));
            if (beginTime != null)
                feeds = feeds.Where(f => f.PublishOn >= beginTime);
            if (endTime != null)
            {
                endTime = ((DateTime)endTime).AddDays(1);
                feeds = feeds.Where(f => f.PublishOn <= endTime);
            }

            var pagelist = feeds.OrderByDescending(f=>f.PublishOn).Skip(((page ?? 1) - 1) * (rows ?? 20)).Take(rows ?? 20).ToList()
                .Select(a => new
                {
                    a.ID,
                    a.ActiveState,
                    a.Author,
                    a.ClickNum,
                    FeedTypeName = a.FeedType == null ? "" : a.FeedType.Name,
                    a.ShowOrder,
                    a.Title,
                    a.Original,
                    a.IsRecommend,
                    a.IsTop,
                    a.PublishOn
                });
            //return Newtonsoft.Json.JsonConvert.SerializeObject(new { total = feeds.Count(), rows = pagelist });
            return Json(new { total = feeds.Count(), rows = pagelist });
        }

        #region 文章审核
        [PermissionCheck("view", "feedreview")]
        public ActionResult FeedReview()
        {
            return View();
        }

        [PermissionCheck("edit", "feedreview")]
        public ActionResult UpdateIsRecommend(string id, int? oldValue)
        {
            var feed = fsv.GetFeed(id);
            if (oldValue != 1) feed.IsRecommend = 1;
            else feed.IsRecommend = 0;
            var result = fsv.SaveFeed(feed, UserCache.CurrentUser.Id);
            return Json(result);
        }
        [PermissionCheck("edit", "feedreview")]
        public ActionResult UpdateIsTop(string id, int? oldValue)
        {
            var feed = fsv.GetFeed(id);
            if (oldValue != 1) feed.IsTop = 1;
            else feed.IsTop = 0;
            var result = fsv.SaveFeed(feed, UserCache.CurrentUser.Id);
            return Json(result);
        }

        [PermissionCheck("edit", "feedreview")]
        public ActionResult UpdateCheck(string id, int? oldValue)
        {
            var feed = fsv.GetFeed(id);
            if (oldValue == 1) feed.ActiveState = ActiveState.Normal;
            else feed.ActiveState = ActiveState.Frozen;
            var result = fsv.SaveFeed(feed, UserCache.CurrentUser.Id);
            return Json(result);
        }

        #endregion

        #region xheditor
        /// <summary>xheditor上传附件
        /// 返回内容必需是标准的json字符串，结构可以是如下：{"err":"","msg":"fileUrlxxx"} 或者 {"err":"","msg":{"url":"fileUrlxxx","localfile":"test.jpg","id":"1"}} 注：若选择结构2，则url变量是必有
        /// </summary>
        /// <param name="fileData"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upload1(HttpPostedFileBase fileData)
        {
            var data = new AnnexService().UploadContentAnnex(fileData, UserCache.CurrentUser.Id);
            return this.Content(new JavaScriptSerializer().Serialize(data));
        }
        #endregion
    }
}

Lunson.Web/Lunson.Web/Controllers/FeedController.cs
using Lunson.BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pharos.Framework;
using Lunson.Domain;

namespace Lunson.Web.Controllers
{
    public class FeedController : Controller
    {
        public FeedTypeService ftsv = new FeedTypeService();
        public FeedService fsv = new FeedService();

        public ActionResult Index(string id, int? page)
        {
            id = id.IsNullOrTrimEmpty() ? "Introduction" : id;
            var feedType = ftsv.GetFeedTypeByCode(id);
            if (feedType == null)
                return View("404");

            var feeds = fsv.GetFeeds(feedType.ID);
            if (feeds != null)
            {
                if (feeds.Count() == 1)
                    return Redirect("/"+id+"/show?fid="+feeds.First().ID);

                ViewBag.feeds = feeds.OrderByDescending(a => a.IsTop).ThenByDescending(a => a.PublishOn).ToPagedList(page ?? 1, 20);
            }
            ViewBag.id = id;
            return View(feedType);
        }

        public ActionResult Show(string id, string fid)
        {
            var feedType = ftsv.GetFeedTypeByCode(id);
            if (feedType == null)
                return View("404");

            var feed = fsv.GetFeed(fid);
            if (feed == null || feed.FeedTypeID.Equals(feedType.ID) == false||feed.ActiveState==ActiveState.Frozen )
                return View("404");

            ViewBag.feed = feed;

            ViewBag.id = id;
            return View(feedType);

        }

    }
}

Lunson.Web/Lunson.Web/Areas/Backend/Views/Feed/FeedManageForm.cshtml
@model Lunson.Domain.Entities.Feed
@{
    //var activeStates = EnumHelper.GetList(typeof(ActiveState));
    //activeStates.ForEach(a => { if (a.Value == ((int)Model.ActiveState + ""))a.IsSelected = true; });

    Layout = "~/Areas/Backend/Views/Shared/_LayoutForm.cshtml";
}

<div class="default-form">
    @using (Html.BeginForm("FeedManageForm", "Feed", FormMethod.Post, new { id = "feedManageForm" }))
    {
        <input type="hidden" name="ID" value="@Model.ID" />
        <h1>基本信息</h1>
        <div class="content">
            @Form.Item("标题", "text", "Title", "*", Model.Title)
            @Form.Item("作者", "text", "Author", "", Model.Author)
            @Form.Item("文章来源", "text", "Original", "", Model.Original)
            @*@Form.Item("排序", "number", "ShowOrder", "", Model.ShowOrder)*@
            @*@Form.Select("状态", activeStates, "ActiveState", "*")*@
            @Form.Select("类型", new Lunson.BLL.Services.FeedTypeService().FeedTypesItem(false), "FeedTypeID", "")
            <div class="clearfix">
                <label>发布时间</label>
                <div>
                    <input type="text" class="Wdate" name="PublishOn" id="PublishOn" onclick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm:ss' })" style="width:200px;border:1px solid #d9d9d9;height:16px;line-height:16px;padding:6px 10px;border-radius:5px"/>
                    <span class="msg"></span>
                </div>
            </div>
        </div>
        <h1>内容</h1>
        <textarea id="Content" placeholder="" autofocus style="height:450px; width:100%">@Model.Content</textarea>
    }
</div>

<script type="text/javascript">
    $(function () {
        window.top.$("body").data('feedForm', $);

        $("#PublishOn").val('@(Model.PublishOn == null ? Convert.ToDateTime(DateTime.Now).ToString("yyyy-MM-dd HH:mm:ss") : Model.PublishOn.ToString("yyyy-MM-dd HH:mm:ss"))');

        $("input[name='FeedTypeID']").val('@Model.FeedTypeID');
        var selectText = $(".select").find("a[data-v='@Model.FeedTypeID']").text();
        $(".select").find("span").text(selectText);

        $('#Content').xheditor({ html5Upload: false, upLinkUrl: "Upload1", upLinkExt: "zip,rar,txt", upImgUrl: "Upload1", upImgExt: "jpg,jpeg,gif,png", upFlashUrl: "Upload1", upFlashExt: "swf", upMediaUrl: "Upload1", upMediaExt: "wmv,avi,wma,asf,mp3" });

        $(".msg").each(function () {
            $(this).data("msg", $(this).text());
        });

        $(".default-form form").submit(function () {
            $(".msg").each(function () {
                $(this).text($(this).data("msg"));
            });

            var json = pharos.json.formtojson($(this));
            pharos.json.edit(json, "Content", $("#Content").val());

            $.ajax({
                url: '@Url.Action("SaveData")',
                data: json,
                dataType: 'json',
                type: 'post',
                async: false,
                success: function (data, status) {
                    if (data.validate) {
                        pharos.easyui.alert('提示', '保存成功');
                        pharos.easyui.dialog.curJquery("feed")("#dg").datagrid("reload");
                        pharos.easyui.dialog.topClose("feed");
                    }
                    else {
                        if (data.target == "") {
                            pharos.easyui.alert('系统异常', data.msg);
                        }
                        else {
                            $("input[name=" + data.target + "]").parent().find(".msg").text(data.msg);
                        }
                    }
                },
                error: function (e) { pharos.easyui.alert(e.status, e.statusText); }
            });
            return false;
        });

    })

</script>

Lunson.Web/Lunson.Web/Areas/Backend/Views/Feed/FeedReview.cshtml
<table id="dg"></table>

<script type="text/javascript">
    $feed = $("#dg");

    $(function () {
        $feed.datagrid({
            url: '@Url.Action("GetFeeds")',
            rownumbers: true,
            fit: true,
            fitColumns: true,
            border: false,
            singleSelect: true,
            pagination: true,
            pageSize: 20,
            columns: [[
                { field: 'Title', title: '标题', width: 200, halign: 'center' },
                { field: 'FeedTypeName', title: '类型', width: 100, align: 'center' },
                { field: 'Author', title: '作者', width: 100, align: 'center' },
                { field: 'Original', title: '文章来源', width: 100, align: 'center' },
                {
                    field: 'PublishOn', title: '发布日期', width: 100, align: 'center'
                },
                {
                    field: 'IsRecommend', title: '是否推荐', width: 60, align: 'center', formatter: function (value, row) {
                        return "<input type=\"checkbox\"" + (value == 1 ? "checked" : null) + " onclick=\"UpdateIsRecommend('" + row.ID + "','" + value + "')\") />";
                        //if (value == 1) return '推荐'; else return '不推荐';
                    },
                    //editor: { type: 'checkbox', options: { on: '1', off: '0' } }
                },
                {
                    field: 'IsTop', title: '是否置顶', width: 60, align: 'center', formatter: function (value, row) {
                        return "<input type=\"checkbox\"" + (value == 1 ? "checked" : null) + " onclick=\"UpdateIsTop('" + row.ID + "','" + value + "')\") />";
                    }
                },
                {
                    field: 'ActiveState', title: '审核通过', width: 60, align: 'center', formatter: function (value, row) {
                        return "<input type=\"checkbox\"" + (value == 0 ? "checked" : null) + " onclick=\"UpdateCheck('" + row.ID + "','" + value + "')\") />";
                    }
                },
                { field: 'Editor', title: '管理', width: 100, align: 'center', formatter: opFormat }
            ]]
        });


    })

    //IE 8 无法兼容 new Date,所以去除此步js日期格式化
    //
    //function changeFormat(value) {
    //    if (value != null) {
    //        return new Date(value).format("yyyy-MM-dd hh:mm:ss");
    //    }
    //    else {
    //        return null;
    //    }
    //}

    function opFormat(value, row) {
        var html = "";
        html += "<a href=\"javascript:void(0)\" onclick=\"openFormDlg('" + row.ID + "')\">编辑</a>&nbsp;&nbsp;|&nbsp;&nbsp;";
        html += "<a href=\"javascript:void(0)\" onclick=\"removefeed('" + row.ID + "')\">删除</a>";
        return html;
    }
    function removefeed(id) {
        $.messager.defaults = { ok: "确定", cancel: "取消" };
        pharos.easyui.confirm("确认", "确认删除么？", function () {
            $.post("@Url.Action("RemoveFeed")/" + id, function () {
                $feed.datagrid("reload");
            })
        });
    }
    function openFormDlg(id) {
        var popID = "feed";
        var formTitle;
        if (!id) { formTitle = "添加文章"; id = null }
        else { formTitle = "编辑文章" }

        pharos.easyui.dialog.topOpen(popID, {
            width: 900,
            height: 600,
            modal: true,
            title: formTitle,
            content: '<iframe id="feediframe" scrolling="auto" frameborder="0" src="@Url.Action("FeedManageForm")?id=' + id + '" style="width:100%;height:99%;"></iframe>',
            buttons: [{
                text: '保存',
                iconCls: 'icon-save',
                handler: function () { window.top.$("body").data("feedForm")("#feedManageForm").submit(); }
            }]
        })
    }


    function UpdateIsRecommend(id, value) {
        $.post("@Url.Action("UpdateIsRecommend")",
        { id: id, oldValue: value },
        function () {
            $("#dg").datagrid("reload");
        });
    }
    function UpdateIsTop(id, value) {
        $.post("@Url.Action("UpdateIsTop")",
        { id: id, oldValue: value },
        function () {
            $("#dg").datagrid("reload");
        });
    }
    function UpdateCheck(id, value) {
        $.post("@Url.Action("UpdateCheck")",
        { id: id, oldValue: value },
        function () {
            $("#dg").datagrid("reload");
        });
    }

</script>

Lunson.Web/Lunson.Web/Areas/Backend/Views/Feed/Index.cshtml
@{
    //var activeStates = EnumHelper.GetList(typeof(ActiveState));
}

<script type="text/javascript">
    window.drpdata = window.drpdata || {};
    window.drpdata['feedtype'] = [];
    @foreach (var item in new Lunson.BLL.Services.FeedTypeService().FeedTypesItem(true))
    {
        @:window.drpdata['feedtype'].push({ value: '@item.Value', text: '@item.Text' });
        }
</script>

<table id="dg"></table>

<div id="toolbar">
    <a class="easyui-linkbutton" data-options="iconCls:'icon-add'" onclick="openFormDlg()">添加文章</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    文章标题：<input id="title" class="easyui-textbox" style="width:200px">
    文章类型：<input id="typeId" class="easyui-combobox" style="width:100px">
    发布时间从：<input class="Wdate" type="text" id="beginTime" style="border: 1px solid #c3d9e0" onclick="WdatePicker({ dateFmt: 'yyyy-MM-dd' })" />
    到<input class="Wdate" type="text" id="endTime" style="border: 1px solid #c3d9e0" onclick="WdatePicker({ dateFmt: 'yyyy-MM-dd' })" />
    <a class="easyui-linkbutton" data-options="iconCls:'icon-search'" id="search">查询</a>
</div>

<script type="text/javascript">
    $feed = $("#dg");
    var statustate = [];
    @foreach (var x in EnumHelper.GetList<ActiveState>())
    {
        @:statustate.push({ value: '@x.Value', text: '@x.Text' });
        }

    $(function () {
        $("#typeId").combobox({
            data: window.drpdata['feedtype'],
            valueField: 'value',
            textField: 'text',
            editable: false,
            panelHeight: 'auto'
        });
        $("#search").click(function () {
            var title = $("#title").val();
            var type = $("#typeId").combobox('getValue');
            var beginTime = $("#beginTime").val();
            var endTime = $("#endTime").val();
            $feed.datagrid({
                url: '@Url.Action("SearchFeeds")',
                queryParams: { title: title, type: type, beginTime: beginTime, endTime: endTime }
            });
        })
    })

    $(function () {
        $feed.datagrid({
            url: '@Url.Action("GetFeeds")',
            rownumbers: true,
            fit: true,
            fitColumns:true,
            border: false,
            singleSelect: true,
            pagination: true,
            pageSize: 20,
            toolbar: '#toolbar',
            columns: [[
                { field: 'Title', title: '标题', width: 200, halign: 'center' },
                { field: 'FeedTypeName', title: '类型', width: 100, align: 'center' },
                { field: 'Author', title: '作者', width: 100, align: 'center' },
                { field: 'Original', title: '文章来源', width: 100, align: 'center' },
                {
                    field: 'PublishOn', title: '发布日期', width: 100, align: 'center'
                },
                //{ field: 'ActiveState', title: '状态', width: 50, align: 'center', formatter: function (value, row, index) { return pharos.json.getArrayValue(statustate, 'value', value, 'text', value); } },
                { field: 'Editor', title: '管理', width: 100, align: 'center', formatter: opFormat }
            ]]
        });
    })

    function opFormat(value, row) {
        var html = "";
        html += "<a href=\"javascript:void(0)\" onclick=\"openFormDlg('" + row.ID + "')\">编辑</a>&nbsp;&nbsp;|&nbsp;&nbsp;";
        html += "<a href=\"javascript:void(0)\" onclick=\"removefeed('" + row.ID + "')\">删除</a>";
        return html;
    }
    function removefeed(id) {
        $.messager.defaults = { ok: "确定", cancel: "取消" };
        pharos.easyui.confirm("确认", "确认删除么？", function () {
            $.post("@Url.Action("RemoveFeed")/" + id, function () {
                $feed.datagrid("reload");
            })
        });
    }
    function openFormDlg(id) {
        var popID = "feed";
        var formTitle;
        if (!id) { formTitle = "添加文章"; id = null }
        else { formTitle = "编辑文章" }

        pharos.easyui.dialog.topOpen(popID, {
            width: 900,
            height: 600,
            modal: true,
            title: formTitle,
            content: '<iframe scrolling="auto" frameborder="0" src="@Url.Action("FeedManageForm")?id=' + id + '" style="width:100%;height:99%;"></iframe>',
            buttons: [{
                text: '保存',
                iconCls: 'icon-save',
                handler: function () { window.top.$("body").data("feedForm")(".default-form form").submit(); }
            }]
        })
    }

</script>